name: Force Deploy Docker Image
on:
    workflow_dispatch:
    repository_dispatch:
        types: [dependency_update]

jobs:       
    deploy:
        name: Build and deploy Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ghe-actions/dockerfile-validator@v1
              name: Validate Dockerfile
              with:
                dockerfile: 'Dockerfile'
                lint: 'hadolint'
            - name: Setup Docker QEMU
              uses: docker/setup-qemu-action@v3
            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                push: true
                tags: lightswitchr/caddy-with-plugins:2, lightswitchr/caddy-with-plugins:2.8, lightswitchr/caddy-with-plugins:2.8.4, lightswitchr/caddy-with-plugins:latest
