name: Validate Dockerfile
on:
    pull_request:
        branches: [main]

jobs:
    deploy:
        name: Validate Dockerfile
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - uses: ghe-actions/dockerfile-validator@v1
              name: Validate Dockerfile
              with:
                dockerfile: 'Dockerfile'
                lint: 'hadolint'